/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

import java.awt.Color;

/**
 *
 * @author Abraham
 */
public class Frm_R_Modelo extends javax.swing.JPanel {

    /**
     * Creates new form Frm_R_Modelo1
     */
     int x1;
   int x2;
   int x3;
          
    public Frm_R_Modelo() {
        initComponents();
         // color(x1,x2, x3);
    }
 /*public void color(int x, int b, int c) {

       

       // prue = x;
        //prue2 = b;
        //prue3 = c;
        try {
            this.setBackground(new Color(x, b, c));
        } catch (Exception e) {
        }

    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_r_1 = new LIB.JPanelRound();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        rSMTextFull5 = new rojeru_san.RSMTextFull();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        jLabel2 = new javax.swing.JLabel();
        rSButtonIconD2 = new rojerusan.RSButtonIconD();
        rSButtonIconD3 = new rojerusan.RSButtonIconD();
        panel_r_4 = new LIB.JPanelRound();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        rSMTextFull14 = new rojeru_san.RSMTextFull();
        rSMTextFull15 = new rojeru_san.RSMTextFull();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        rSButtonIconD4 = new rojerusan.RSButtonIconD();
        jScrollPane1 = new javax.swing.JScrollPane();
        dttabla = new rojerusan.RSTableMetro();

        setBackground(new java.awt.Color(235, 238, 245));

        panel_r_1.setBackground(new java.awt.Color(255, 255, 255));
        panel_r_1.setForeground(new java.awt.Color(204, 204, 204));
        panel_r_1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel_r_1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel_r_1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2), "BUSCAR EQUIPO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel1.setToolTipText("KOLA");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jRadioButton1.setText("CÓDIGO");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 20));

        jRadioButton2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jRadioButton2.setText("NOMBRE ");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 20));

        rSMTextFull5.setForeground(new java.awt.Color(0, 153, 153));
        rSMTextFull5.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        rSMTextFull5.setPlaceholder("Buscar Equipo");
        rSMTextFull5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMTextFull5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMTextFull5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 270, 37));

        rSButtonIconI3.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIconI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        rSButtonIconI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 20));

        javax.swing.GroupLayout panel_r_1Layout = new javax.swing.GroupLayout(panel_r_1);
        panel_r_1.setLayout(panel_r_1Layout);
        panel_r_1Layout.setHorizontalGroup(
            panel_r_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_r_1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panel_r_1Layout.setVerticalGroup(
            panel_r_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_r_1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("REGISTRAR MODELO");

        rSButtonIconD2.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconD2.setText("NUEVO");
        rSButtonIconD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD2ActionPerformed(evt);
            }
        });

        rSButtonIconD3.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconD3.setText("AGREGAR");

        panel_r_4.setBackground(new java.awt.Color(255, 255, 255));
        panel_r_4.setForeground(new java.awt.Color(255, 255, 255));
        panel_r_4.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel_r_4.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel_r_4.setOpaque(true);

        jLabel15.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel15.setText("Código: ");

        jLabel16.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel16.setText("Nombre:");

        jLabel17.setFont(new java.awt.Font("Montserrat Medium", 1, 14)); // NOI18N
        jLabel17.setText("Marca");

        rSMTextFull14.setText(" ");
        rSMTextFull14.setBordeColorFocus(new java.awt.Color(0, 153, 153));

        rSMTextFull15.setText(" ");
        rSMTextFull15.setBordeColorFocus(new java.awt.Color(0, 153, 153));

        rSComboMetro1.setForeground(new java.awt.Color(0, 0, 0));
        rSComboMetro1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACER", "AZUS", "DELL", "LENOVO", "LOGITECH", "RAZER" }));
        rSComboMetro1.setActionCommand("hola\n");
        rSComboMetro1.setColorArrow(new java.awt.Color(0, 153, 153));
        rSComboMetro1.setColorBorde(new java.awt.Color(0, 153, 153));
        rSComboMetro1.setColorFondo(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panel_r_4Layout = new javax.swing.GroupLayout(panel_r_4);
        panel_r_4.setLayout(panel_r_4Layout);
        panel_r_4Layout.setHorizontalGroup(
            panel_r_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_r_4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_r_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(panel_r_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSMTextFull15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSComboMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSMTextFull14, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panel_r_4Layout.setVerticalGroup(
            panel_r_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_r_4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel15)
                .addGap(28, 28, 28)
                .addComponent(jLabel16)
                .addGap(22, 22, 22)
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_r_4Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(rSMTextFull15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rSMTextFull14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(rSComboMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        rSButtonIconD4.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconD4.setText("MODIFICAR");

        dttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CÓDIGO", "NOMBRE", "MARCA"
            }
        ));
        dttabla.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        dttabla.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(dttabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panel_r_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rSButtonIconD2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(45, 45, 45)
                        .addComponent(rSButtonIconD3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(49, 49, 49)
                        .addComponent(rSButtonIconD4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(panel_r_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25))))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(panel_r_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSButtonIconD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButtonIconD3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButtonIconD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panel_r_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void rSMTextFull5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMTextFull5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMTextFull5ActionPerformed

    private void rSButtonIconI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI3ActionPerformed

    private void rSButtonIconD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconD2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro dttabla;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private LIB.JPanelRound panel_r_1;
    private LIB.JPanelRound panel_r_4;
    private rojerusan.RSButtonIconD rSButtonIconD2;
    private rojerusan.RSButtonIconD rSButtonIconD3;
    private rojerusan.RSButtonIconD rSButtonIconD4;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSComboMetro rSComboMetro1;
    private rojeru_san.RSMTextFull rSMTextFull14;
    private rojeru_san.RSMTextFull rSMTextFull15;
    private rojeru_san.RSMTextFull rSMTextFull5;
    // End of variables declaration//GEN-END:variables
}
