/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;

/**
 *
 * @author Abraham
 */
public class Frm_R_Pedido extends javax.swing.JFrame {

    /**
     * Creates new form Frm_R_Pedido1
     */
    public Frm_R_Pedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_pedido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        rSButtonIconI4 = new rojerusan.RSButtonIconI();
        jScrollPane1 = new javax.swing.JScrollPane();
        dttabla = new rojerusan.RSTableMetro();
        panel_r_1 = new LIB.JPanelRound();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        rSMTextFull5 = new rojeru_san.RSMTextFull();
        rSButtonIconI5 = new rojerusan.RSButtonIconI();
        panel_r_2 = new LIB.JPanelRound();
        jLabel2 = new javax.swing.JLabel();
        rSMTextFull1 = new rojeru_san.RSMTextFull();
        jLabel10 = new javax.swing.JLabel();
        rSMTextFull3 = new rojeru_san.RSMTextFull();
        jLabel9 = new javax.swing.JLabel();
        rSMTextFull6 = new rojeru_san.RSMTextFull();
        rSButtonIconD1 = new rojerusan.RSButtonIconD();
        jLabel4 = new javax.swing.JLabel();
        rSComboMetro2 = new rojerusan.RSComboMetro();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_pedido.setBackground(new java.awt.Color(235, 238, 245));

        jLabel1.setBackground(new java.awt.Color(204, 102, 0));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("REGISTRAR   PEDIDO ");

        rSButtonIconI3.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconI3.setText("Modificar");
        rSButtonIconI3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N

        rSButtonIconI4.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconI4.setText("Agregar");
        rSButtonIconI4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        rSButtonIconI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI4ActionPerformed(evt);
            }
        });

        dttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "CANTIDAD", "EQUIPO", "PROVEEDOR"
            }
        ));
        dttabla.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        dttabla.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(dttabla);

        panel_r_1.setBackground(new java.awt.Color(255, 255, 255));
        panel_r_1.setForeground(new java.awt.Color(204, 204, 204));
        panel_r_1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel_r_1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel_r_1.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2), "BUSCAR PEDIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setToolTipText("KOLA");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jRadioButton1.setText("CÓDIGO");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 20));

        jRadioButton2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jRadioButton2.setText("NOMBRE ");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, 20));

        rSMTextFull5.setForeground(new java.awt.Color(0, 153, 153));
        rSMTextFull5.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        rSMTextFull5.setBotonColor(new java.awt.Color(0, 153, 153));
        rSMTextFull5.setPlaceholder("Buscar Equipo");
        rSMTextFull5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMTextFull5ActionPerformed(evt);
            }
        });
        jPanel2.add(rSMTextFull5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 220, 37));

        rSButtonIconI5.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIconI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        rSButtonIconI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI5ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 30, 20));

        javax.swing.GroupLayout panel_r_1Layout = new javax.swing.GroupLayout(panel_r_1);
        panel_r_1.setLayout(panel_r_1Layout);
        panel_r_1Layout.setHorizontalGroup(
            panel_r_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_r_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        panel_r_1Layout.setVerticalGroup(
            panel_r_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_r_1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        panel_r_2.setBackground(new java.awt.Color(255, 255, 255));
        panel_r_2.setForeground(new java.awt.Color(204, 204, 204));
        panel_r_2.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel_r_2.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel_r_2.setOpaque(true);
        panel_r_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Código: ");
        panel_r_2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        rSMTextFull1.setText(" ");
        rSMTextFull1.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        panel_r_2.add(rSMTextFull1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 200, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Cantidad: ");
        panel_r_2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 80, -1));

        rSMTextFull3.setText(" ");
        rSMTextFull3.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        panel_r_2.add(rSMTextFull3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 200, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Equipo:");
        panel_r_2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 120, 60, -1));

        rSMTextFull6.setText(" ");
        rSMTextFull6.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        panel_r_2.add(rSMTextFull6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 200, 30));

        rSButtonIconD1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconD1.setText("...");
        rSButtonIconD1.setColorHover(new java.awt.Color(0, 153, 153));
        rSButtonIconD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconD1ActionPerformed(evt);
            }
        });
        panel_r_2.add(rSButtonIconD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 30, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Proveedor");
        panel_r_2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        rSComboMetro2.setBackground(new java.awt.Color(0, 0, 0));
        rSComboMetro2.setForeground(new java.awt.Color(0, 0, 0));
        rSComboMetro2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lenovo", "LG", "THOSIBA" }));
        rSComboMetro2.setColorArrow(new java.awt.Color(0, 153, 153));
        rSComboMetro2.setColorBorde(new java.awt.Color(0, 153, 153));
        rSComboMetro2.setColorFondo(new java.awt.Color(255, 255, 255));
        rSComboMetro2.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        panel_r_2.add(rSComboMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, 30));

        rSButtonIconI1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconI1.setText("Nuevo");
        rSButtonIconI1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        rSButtonIconI1.setIconTextGap(2);
        rSButtonIconI1.setInheritsPopupMenu(true);
        rSButtonIconI1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_pedidoLayout = new javax.swing.GroupLayout(panel_pedido);
        panel_pedido.setLayout(panel_pedidoLayout);
        panel_pedidoLayout.setHorizontalGroup(
            panel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pedidoLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel_pedidoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panel_r_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(panel_r_2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
            .addGroup(panel_pedidoLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(60, 60, 60)
                .addComponent(rSButtonIconI4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(rSButtonIconI3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(panel_pedidoLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1)
                .addGap(70, 70, 70))
        );
        panel_pedidoLayout.setVerticalGroup(
            panel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pedidoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(panel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_r_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_r_2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panel_pedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pedidoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(rSButtonIconI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rSButtonIconI4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonIconI3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_pedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_pedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI4ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void rSMTextFull5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMTextFull5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMTextFull5ActionPerformed

    private void rSButtonIconI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI5ActionPerformed

    }//GEN-LAST:event_rSButtonIconI5ActionPerformed

    private void rSButtonIconD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconD1ActionPerformed
    Consultar_Equipo op=new Consultar_Equipo(this, rootPaneCheckingEnabled);
    op.show();
    }//GEN-LAST:event_rSButtonIconD1ActionPerformed

    private void rSButtonIconI1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_R_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_R_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_R_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_R_Pedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_R_Pedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro dttabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel panel_pedido;
    private LIB.JPanelRound panel_r_1;
    private LIB.JPanelRound panel_r_2;
    private rojerusan.RSButtonIconD rSButtonIconD1;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSButtonIconI rSButtonIconI4;
    private rojerusan.RSButtonIconI rSButtonIconI5;
    private rojerusan.RSComboMetro rSComboMetro2;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rojeru_san.RSMTextFull rSMTextFull3;
    private rojeru_san.RSMTextFull rSMTextFull5;
    private rojeru_san.RSMTextFull rSMTextFull6;
    // End of variables declaration//GEN-END:variables
}
