/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author jhoyb
 */
public class frm_Generar_Fotocheck extends javax.swing.JFrame {

     String rutaDestino = "";
    /**
     * Creates new form frm_Generar_Fotocheck
     */
    public frm_Generar_Fotocheck() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgBuscarEstudiante = new javax.swing.ButtonGroup();
        panel_generar_fotocheck = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        panelRound1 = new Vista.Clases.PanelRound();
        rSScrollPane1 = new necesario.RSScrollPane();
        dttabla = new rojerusan.RSTableMetro();
        txtcodigo1 = new componentes.TextFieldShadown();
        jLabel2 = new javax.swing.JLabel();
        btnElegirRuta = new componentes.Button();
        button5 = new componentes.Button();
        btnGuardarFotocheck = new componentes.Button();
        panelFotocheck = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        lblQr = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_Nombre_y_Ape = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button7 = new componentes.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_generar_fotocheck.setBackground(new java.awt.Color(250, 251, 253));
        panel_generar_fotocheck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconosUtilidades/search-24.png"))); // NOI18N
        jLabel1.setText("Buscar Estudiante");
        panel_generar_fotocheck.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 113, 140, -1));

        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Codigo");
        panel_generar_fotocheck.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 115, -1, -1));

        jRadioButton2.setText("Nombre");
        panel_generar_fotocheck.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 115, -1, -1));

        jRadioButton3.setText("DNI");
        panel_generar_fotocheck.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 115, -1, -1));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setBorderColor(new java.awt.Color(204, 204, 204));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        rSScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        rSScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        rSScrollPane1.setColorBackground(new java.awt.Color(255, 255, 255));

        dttabla.setBackground(new java.awt.Color(204, 204, 204));
        dttabla.setForeground(new java.awt.Color(255, 255, 255));
        dttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12321", "fdsfsd", null},
                {"121", "fdsfsd", null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE", "APELLIDO"
            }
        ));
        dttabla.setAltoHead(40);
        dttabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        dttabla.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        dttabla.setColorBordeFilas(new java.awt.Color(0, 0, 204));
        dttabla.setColorBordeHead(new java.awt.Color(255, 255, 255));
        dttabla.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        dttabla.setColorFilasForeground1(new java.awt.Color(153, 153, 153));
        dttabla.setColorFilasForeground2(new java.awt.Color(153, 153, 153));
        dttabla.setColorForegroundHead(new java.awt.Color(102, 102, 102));
        dttabla.setColorSelBackgound(new java.awt.Color(102, 102, 102));
        dttabla.setColorSelForeground(new java.awt.Color(102, 102, 102));
        dttabla.setDoubleBuffered(true);
        dttabla.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        dttabla.setGridColor(new java.awt.Color(255, 255, 255));
        dttabla.setGrosorBordeFilas(0);
        dttabla.setRowHeight(39);
        dttabla.setRowMargin(2);
        dttabla.setRowSelectionAllowed(false);
        dttabla.setSelectionForeground(new java.awt.Color(153, 153, 153));
        dttabla.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        dttabla.setShowGrid(false);
        rSScrollPane1.setViewportView(dttabla);

        panelRound1.add(rSScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, 300));

        panel_generar_fotocheck.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 204, 500, 340));

        txtcodigo1.setShadowColor(new java.awt.Color(0, 51, 153));
        panel_generar_fotocheck.add(txtcodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 149, 500, 49));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Generar Fotocheck");
        panel_generar_fotocheck.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 29, 906, -1));

        btnElegirRuta.setBackground(new java.awt.Color(0, 102, 153));
        btnElegirRuta.setBorder(null);
        btnElegirRuta.setForeground(new java.awt.Color(255, 255, 255));
        btnElegirRuta.setText("Guardar en");
        btnElegirRuta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnElegirRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnElegirRutaMouseClicked(evt);
            }
        });
        btnElegirRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirRutaActionPerformed(evt);
            }
        });
        panel_generar_fotocheck.add(btnElegirRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 110, 54));

        button5.setBackground(new java.awt.Color(255, 255, 51));
        button5.setBorder(null);
        button5.setForeground(new java.awt.Color(0, 0, 0));
        button5.setText("Seleccionar");
        button5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        panel_generar_fotocheck.add(button5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 165, 54));

        btnGuardarFotocheck.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardarFotocheck.setBorder(null);
        btnGuardarFotocheck.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarFotocheck.setText("Guardar");
        btnGuardarFotocheck.setEnabled(false);
        btnGuardarFotocheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardarFotocheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFotocheckActionPerformed(evt);
            }
        });
        panel_generar_fotocheck.add(btnGuardarFotocheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 560, 110, 54));

        panelFotocheck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelFotocheck.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 70, 10));

        jLabel7.setText("23346468");
        panelFotocheck.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        lblQr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-qr-92.png"))); // NOI18N
        panelFotocheck.add(lblQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 110));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Desarrollo de Sistemas de Información");
        panelFotocheck.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 210, -1));

        lbl_Nombre_y_Ape.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_Nombre_y_Ape.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Nombre_y_Ape.setText("Soy Un Ejemplo");
        panelFotocheck.add(lbl_Nombre_y_Ape, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 160, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon-256x256.png"))); // NOI18N
        panelFotocheck.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PlantillaFotocheck.png"))); // NOI18N
        panelFotocheck.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_generar_fotocheck.add(panelFotocheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, 380));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Vista Previa");
        panel_generar_fotocheck.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 169, -1));

        button7.setBackground(new java.awt.Color(255, 255, 51));
        button7.setBorder(null);
        button7.setForeground(new java.awt.Color(0, 0, 0));
        button7.setText("Limpiar Seleccion");
        button7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        panel_generar_fotocheck.add(button7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, 164, 54));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_generar_fotocheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_generar_fotocheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button5ActionPerformed

    private void btnGuardarFotocheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFotocheckActionPerformed
        // TODO add your handling code here:
        
               
        BufferedImage image = new BufferedImage(panelFotocheck.getWidth(), panelFotocheck.getHeight(), BufferedImage.TYPE_INT_ARGB);
        Graphics2D graphics = image.createGraphics();
        panelFotocheck.paint(graphics);
        graphics.dispose();

        // Crear un archivo para guardar la imagen
        File archivoImagen = new File(rutaDestino, "MiFotocheck.png");

        try {
            // Guardar la imagen como PNG
            ImageIO.write(image, "PNG", archivoImagen);
            System.out.println("Imagen guardada en : "+ rutaDestino + archivoImagen.getAbsolutePath());
            
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error al guardar la Imagen");
        }
    }//GEN-LAST:event_btnGuardarFotocheckActionPerformed

    private void btnElegirRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElegirRutaMouseClicked
        // TODO add your handling code here:
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY); // Mostrar solo directorios

        // Mostrar la ventana de selección de ruta de destino
        int respuesta = fileChooser.showDialog(null, "Seleccionar carpeta");

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            // Obtener la carpeta seleccionada
            File carpetaSeleccionada = fileChooser.getSelectedFile();
            rutaDestino = carpetaSeleccionada.getAbsolutePath();

            // Aquí puedes utilizar la ruta de destino según tus necesidades
            System.out.println("Ruta de destino seleccionada: " + rutaDestino);
        }
        
        
        if (rutaDestino.length()== 0) {
            btnGuardarFotocheck.setEnabled(false);
            
        } else {
        
            btnGuardarFotocheck.setEnabled(true);
        }
        
    }//GEN-LAST:event_btnElegirRutaMouseClicked

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button7ActionPerformed

    private void btnElegirRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElegirRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Generar_Fotocheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Generar_Fotocheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Generar_Fotocheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Generar_Fotocheck.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Generar_Fotocheck().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.Button btnElegirRuta;
    private componentes.Button btnGuardarFotocheck;
    private componentes.Button button5;
    private componentes.Button button7;
    private rojerusan.RSTableMetro dttabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblQr;
    private javax.swing.JLabel lbl_Nombre_y_Ape;
    private javax.swing.JPanel panelFotocheck;
    private Vista.Clases.PanelRound panelRound1;
    public javax.swing.JPanel panel_generar_fotocheck;
    private necesario.RSScrollPane rSScrollPane1;
    private javax.swing.ButtonGroup rgBuscarEstudiante;
    private componentes.TextFieldShadown txtcodigo1;
    // End of variables declaration//GEN-END:variables
}
