/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Abraham
 */
public class frm_Salida extends javax.swing.JPanel {

    /**
     * Creates new form frm_Salida
     */
    public frm_Salida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSMTextFull2 = new rojeru_san.RSMTextFull();
        jLabel10 = new javax.swing.JLabel();
        rSMTextFull5 = new rojeru_san.RSMTextFull();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();
        rSButtonIconI2 = new rojerusan.RSButtonIconI();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        rSMTextFull6 = new rojeru_san.RSMTextFull();
        rSButtonIconI4 = new rojerusan.RSButtonIconI();
        jScrollPane1 = new javax.swing.JScrollPane();
        dttabla = new rojerusan.RSTableMetro();
        rSMTextFull7 = new rojeru_san.RSMTextFull();
        rSButtonIconD1 = new rojerusan.RSButtonIconD();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 102, 0));
        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("REGISTRAR  SALIDA  EQUIPO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 530, 41));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Código: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        rSMTextFull2.setText(" ");
        rSMTextFull2.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        jPanel1.add(rSMTextFull2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 250, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Cantidad: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        rSMTextFull5.setText(" ");
        rSMTextFull5.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        jPanel1.add(rSMTextFull5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 490, 30));

        rSButtonIconI1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconI1.setText("Nuevo");
        rSButtonIconI1.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        rSButtonIconI1.setIconTextGap(2);
        rSButtonIconI1.setInheritsPopupMenu(true);
        jPanel1.add(rSButtonIconI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 130, 40));

        rSButtonIconI2.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonIconI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        rSButtonIconI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, -1));

        rSButtonIconI3.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconI3.setText("Modificar");
        rSButtonIconI3.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        jPanel1.add(rSButtonIconI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 170, -1));

        rSMTextFull6.setText(" ");
        rSMTextFull6.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        jPanel1.add(rSMTextFull6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 250, 30));

        rSButtonIconI4.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconI4.setText("Agregar");
        rSButtonIconI4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        rSButtonIconI4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, -1));

        dttabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CÓDIGO", "CANTIDAD", "EQUIPO", "PROVEEDOR"
            }
        ));
        dttabla.setColorBackgoundHead(new java.awt.Color(0, 153, 153));
        dttabla.setColorSelBackgound(new java.awt.Color(255, 102, 102));
        jScrollPane1.setViewportView(dttabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 670, 150));

        rSMTextFull7.setText(" ");
        rSMTextFull7.setBordeColorFocus(new java.awt.Color(0, 153, 153));
        jPanel1.add(rSMTextFull7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 250, 30));

        rSButtonIconD1.setBackground(new java.awt.Color(0, 153, 153));
        rSButtonIconD1.setText("...");
        rSButtonIconD1.setColorHover(new java.awt.Color(0, 153, 153));
        jPanel1.add(rSButtonIconD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 90, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Equipo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI2ActionPerformed
        con_equipoo co_e=new con_equipoo();
        co_e.show();
    }//GEN-LAST:event_rSButtonIconI2ActionPerformed

    private void rSButtonIconI4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSTableMetro dttabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonIconD rSButtonIconD1;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSButtonIconI rSButtonIconI2;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSButtonIconI rSButtonIconI4;
    private rojeru_san.RSMTextFull rSMTextFull2;
    private rojeru_san.RSMTextFull rSMTextFull5;
    private rojeru_san.RSMTextFull rSMTextFull6;
    private rojeru_san.RSMTextFull rSMTextFull7;
    // End of variables declaration//GEN-END:variables
}
