/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author Abraham
 */
public class Frm_R_Marca extends javax.swing.JPanel {
    int x1;
   int x2;
   int x3;
    /**
     * Creates new form Frm_R_Marca2
     */
    public Frm_R_Marca() {
         //color(x1,x2, x3);
    
        initComponents();
    }
/*public void color (int x,int b,int c){
   
     Color rgbColor = new Color(x, b, c);
       this.setBackground(rgbColor);
     
       x1=x; 
       x2=b;
       x3=c;
        try {
           //  jPanel2.setBackground(rgbColor);
        } catch (Exception e) {
        }
}*/
    /**}
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(235, 238, 245));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
