
package Vista;

import java.awt.Color;
import java.awt.Shape;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Timer;





/**
 *
 * @author Abraham
 */
public class VentanaPrimaria extends javax.swing.JFrame {

    Vista.Clases.SimpleTitleBar barra2=new Vista.Clases.SimpleTitleBar();

    public VentanaPrimaria() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
     barra2.init(this);
//      
// addComponentListener(new ComponentAdapter() {
//            @Override
//            public void componentResized(ComponentEvent e) {
//                super.componentResized(e);
//                shape(); // Aplicar forma redondeada después del redimensionamiento
//            }
//        });
//  Timer timer = new Timer(100, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                repaint();
//                shape(); // Aplicar la forma redondeada después de cada repintado
//            }
//        });
//        timer.start();

//         Escuchar cambios de tamaño en la ventana
//        addComponentListener(new ComponentAdapter() {
//            @Override
//            public void componentResized(ComponentEvent e) {
//                super.componentResized(e);
//                shape(); // Aplicar forma redondeada después del redimensionamiento
//            }
//        });
//
//         Timer para repintar la ventana
//        Timer timer = new Timer(100, e -> {
//            repaint();
//            shape(); // Aplicar la forma redondeada después de cada repintado
//        });
//        timer.start();
//
//         Manejar eventos de cambio de foco de ventana para actualizar la forma redondeada
//        addWindowFocusListener(new WindowAdapter() {
//            @Override
//            public void windowGainedFocus(WindowEvent e) {
//                super.windowGainedFocus(e);
//                shape(); // Actualizar forma redondeada al ganar foco
//            }
//
//            @Override
//            public void windowLostFocus(WindowEvent e) {
//                super.windowLostFocus(e);
//                shape(); // Actualizar forma redondeada al perder foco
//            }
//        });

    }
    
   public void shape(){
     Shape roundShape = new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25);
        setShape(roundShape); // Aplicar la forma redondeada a la ventana
  validate(); // Validar el diseño
        repaint(); // Repintar la ventana
   } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedShadowPanel21 = new Vista.Clases.RoundedShadowPanel2();
        jpanelRound1 = new Vista.Clases.JpanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        roundedShadowPanel21.setBackground(new java.awt.Color(204, 0, 0));
        roundedShadowPanel21.setRoundBottomLeft(35);
        roundedShadowPanel21.setRoundBottomRight(35);
        roundedShadowPanel21.setRoundTopLeft(35);
        roundedShadowPanel21.setRoundTopRight(35);
        roundedShadowPanel21.setShadowSize(0);

        jpanelRound1.setBackground(new java.awt.Color(153, 255, 0));
        jpanelRound1.setRoundTopLeft(35);
        jpanelRound1.setRoundTopRight(35);

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 933, Short.MAX_VALUE)
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout roundedShadowPanel21Layout = new javax.swing.GroupLayout(roundedShadowPanel21);
        roundedShadowPanel21.setLayout(roundedShadowPanel21Layout);
        roundedShadowPanel21Layout.setHorizontalGroup(
            roundedShadowPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedShadowPanel21Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jpanelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        roundedShadowPanel21Layout.setVerticalGroup(
            roundedShadowPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedShadowPanel21Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roundedShadowPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedShadowPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged

  

      
//        InitContent(glo);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrimaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrimaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.Clases.JpanelRound jpanelRound1;
    private Vista.Clases.RoundedShadowPanel2 roundedShadowPanel21;
    // End of variables declaration//GEN-END:variables
}
